### PR TITLE
add set header height function

### PR DESCRIPTION
**Pull request by TVMD**
Allow dynamic set header height.

### CODE REVIEW

**Comment by benevbright** [comment]
Hi, thanks for the PR. 
Unfortunately, I can't imagine how it works. 
Just manipulating that object gives you the desired effect?

Could you give me an example of usage and the idea of when you need this?

**Comment by TVMD** [comment]
Hi, I need to change header height depend on data that come from <WrapScreen/>.
My idea is set it like usual then when the the layout change following the data, I just set new height for the header then easy gain what I want.

**Comment by benevbright** [comment]
Thanks for the explanation. 
I got it. Does it work fine? I'm surprised a bit that it's working...

**Comment by TVMD** [comment]
Yes it does. It work just like what I want

**Comment by benevbright** [comment]
Thanks. `3.0.4` includes this fix.

**Pull request merged**
