### PR TITLE
Custom Component

### PR DESCRIPTION
**Pull request by misaku**
i used code of header and try to fix to use custom header.

### CODE REVIEW

**Comment by benevbright** [comment]
@misaku Thanks very much for your PR.
Could you add an example in `/example` too, so let me test on iOS and Android?

**Comment by misaku** [comment]
@benevbright  i put in CustomComponent.MD, but is easy,

```JS
import { CustomComponent } from 'react-navigation-collapsible';

// USE
class Settings extends Component {
    static navigationOptions = ({ navigation }) => {
        const { params = {} } = navigation.state;
        return {
            header: prop => ( // This didn't workout
                <CustomComponent {...prop}>
                                <Nav
                                    title="Settings"
                                    navigation={navigation}
                                    onPressRight={params.handleLogout}
                                    rightName="Log out"
                                    leftIcon={{
                                        type: 'ionicon',
                                        name: 'md-list',
                                        size: 26,
                                    }}
                                />
                </CustomComponent>
            )
        }
    }
...
```

**Comment by benevbright** [comment]
@misaku yes, but it would be good if we had a sample in `/example`, otherwise I have to add myself anyway. 
And It would be easier to communicate between us during the review.

**Comment by misaku** [comment]
good idea, i will change this and send again =)

**Comment by misaku** [comment]
sorry i cant had time to do yet, but will provide this in this weekend =)

**Comment by benevbright** [comment]
no worries! Thanks :)

**Comment by nicoache1** [comment]
Any news about this?

**Comment by misaku** [comment]
i change to test

**Comment by misaku** [comment]
sorry for the delay

**Comment by benevbright** [comment]
Hey, @misaku  I feel very sorry. I apology I didn't know that you added the example a long time ago. 
I don't understand how I missed that... 

Now, https://github.com/benevbright/react-navigation-collapsible/pull/103 (v5 support) is almost ready so we need to rewrite this. Let me check if I can implement this code on v5.

**Pull request closed without merging**
