### PR TITLE
Support react-navigation v3

### PR DESCRIPTION
**Pull request by benevbright**
Issue: #49 

This PR is on progress.

### CODE REVIEW

**Comment by nonotest** [comment]
hello, what is this missing now? keen to put some effort in this weekend

**Comment by benevbright** [comment]
Hi, The collapsible header + material tab combination is still not working. 
nov-30-2018 10-52-22 am

Actually, I'm thinking if I should rewrite this module with new header component, which derives https://github.com/react-navigation/react-navigation-stack 's Header component. (But I'm just thinking right now 😁)
Because I feel it's difficult to do something with current code which is just modifying the style, for example adding a new feature like iOS 11 style big header.

**Comment by benevbright** [comment]
Looks like it's done..!
Updating the document need to be done.

jan-28-2019 2-06-53 am

**Comment by emmx** [comment]
Looks awesome! I'll be doing extensive use of this in the following days. I'll be reporting back in case anything breaks. Thanks.

**Comment by Jalson1982** [comment]
Is it working also on swipe or just on tab press?

**Comment by benevbright** [comment]
> Is it working also on swipe or just on tab press?

Sure. :)

**Comment by benevbright** [comment]
@emmx Thanks a lot :)

**Comment by paolospag** [comment]
@benevbright about "share animated value for all tabs", is it possible to achieve this with custom tabs navigator like old advanced screen example or it works just with react navigation tabs?

**Comment by benevbright** [comment]
@paolospag Hi, unfortunately, this module only works with `react-navigation`. But you can still get an idea from that commit how to achieve it with other Tabs.

**Pull request merged**
